config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'books#index'
  resources :books       #, only: [:index, :show]
  resources :categories
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  #namespace :admin do
    # resources :books, except: [:index, :show]
  #end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord

  has_many :authorings
  has_many :books, through: :authorings

end

app/models/authoring.rb
class Authoring < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord

  validates :name, :body, :all_categories, :all_authors, presence: true

  mount_uploader :image, ImageUploader
  has_many :categorizings, dependent: :destroy
  has_many :authorings, dependent: :destroy
  has_many :authors, through: :authorings
  has_many :categories, through: :categorizings


  def all_categories
    self.categories.map(&:name).join(', ')
  end

  def all_categories=(names)

    self.categories = names.split(',').map do |name|
      Category.where(name: name.strip).first_or_create!
    end

  end


  def all_authors
    self.authors.map(&:name).join(', ')
  end

  def all_authors=(names)
    self.authors = names.split(',').map do |name|
      Author.where(name: name.strip).first_or_create!
    end
  end

end

app/models/categorizing.rb
class Categorizing < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizings
  has_many :books, through: :categorizings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:edit, :update, :destroy]

  # GET /books
  # GET /books.json


  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to [:admin, @book], success: 'Книга была добавлена в библиотеку.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, danger: 'Книга не создана.' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to [:admin, @book], success: 'Книга была обновлена.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, danger: 'Книга не обновлена.' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, success: 'Книга была удалена из библиотеки.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :body, :image, :all_categories, :all_authors)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!

  def index
      @authors = Author.all
  end

  def show
    @author = Author.find_by(name: params[:id])
    @books = @author.books
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :body, :image)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(name: params[:id])
    @books = @category.books
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(name)
        {
          success: "alert-success",
          error: "alert-danger",
          danger: "alert-danger",
          alert: "alert-warning",
          notice: "alert-info"

        }[name.to_sym] || name
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_form.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger"
  <h5><%= t('common.errors') %></h5>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
</div>
<% end %>

<hr />
<%= form_for [:admin, @book], html: {multipart: true} do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :all_categories %>
    <%= form.text_field :all_categories, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :all_authors %>
    <%= form.text_field :all_authors, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Добавить' %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Показать', @book, class: 'btn btn-primary' %>
<%= link_to 'Назад', books_path, class: 'btn btn-primary' %>

app/views/admin/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Назад', books_path, class: 'btn btn-primary' %>

app/views/authors/index.html.erb
<h1>Все авторы</h1>
<hr />

<% @authors.each do |author| %>
    <small>
      <h2><%= link_to author.name, author %></h2>
    </small>


<% end %>

app/views/authors/show.html.erb
<h1>Весь каталог книг автора <%= @author.name %></h1>
<hr />

<% if @author.books.empty? %>
  <h2>Этот автор пока не имеет книг</h2>
  <% else %>
  <%= render @author.books %>
  <% end %>

app/views/books/_book.html.erb
<article class="book">
  <small>

    <h2><%= link_to book.name, book_path(book) %></h2>

    <%= link_to 'Редактировать', edit_book_path(book) %>
    |
    <%= link_to 'Удалить', book_path(book), method: :delete, data: { confirm: 'Вы уверенны?' } %> <br />

  </small>

  автор(ы): <%= raw book.authors.map(&:name).map{ |t| link_to t, author_path(t), class: 'tag tag-primary' }.join(' ') %><br />

  категория: <%= raw book.categories.map(&:name).map{ |t| link_to t, category_path(t), class: 'tag tag-primary' }.join(' ') %>

  <section class="clearfix">

  <%= image_tag book.image.url(:thumb), class: 'img-thumbnail thumb' if book.image? %>

  <%= book.body %>

  </section>


</article>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Добавить' %>
  </div>
<% end %>

app/views/books/index.html.erb
<table>
  <thead>
  </thead>

  <tbody>
    <h1>Все книги</h1>
    <hr />
    <div class="book_post">
    <% @books.each do |book| %>
        <small>
          <h2><%= link_to book.name, book %></h2>
          <%= link_to 'Редактировать', edit_book_path(book) %>
          |
          <%= link_to 'Удалить', book_path(book), method: :delete, data: { confirm: 'Вы уверенны?' } %> <br />

          автор(ы): <%= raw book.authors.map(&:name).map{ |t| link_to t, author_path(t), class: 'tag tag-primary' }.join(' ') %><br />

          категория: <%= raw book.categories.map(&:name).map{ |t| link_to t, category_path(t), class: 'tag tag-primary' }.join(' ') %>
        </small>
        <section class="book-body clearfix">
        <%= image_tag book.image.url(:thumb), class: 'img-thumbnail thumb img-show' if book.image? %>
        <%= book.body %>
        </section>

        <hr />
    <% end %>
  </div>

  </tbody>
</table>

<br>

app/views/books/show.html.erb
<h2>
  <%= @book.name %>
</h2>
<section class="footer">
  <%= link_to 'Редактировать', edit_book_path(@book) %>
  |
  <%= link_to 'Удалить', book_path(@book), method: :delete, data: { confirm: 'Вы увереннны?' } %><br />

автор(ы): <%= raw @book.authors.map(&:name).map{ |t| link_to t, author_path(t), class: 'tag tag-primary' }.join(' ') %><br />

категория: <%= raw @book.categories.map(&:name).map{ |t| link_to t, category_path(t), class: 'tag tag-primary' }.join(' ') %>
</section>
<%= image_tag @book.image.url(:large), class: 'img-show' if @book.image? %>
<p>
  <strong>Описание:</strong>
  <%= @book.body %>
</p>

<section class="footer">

</section>

app/views/categories/index.html.erb
<h1>Все категории</h1>
<hr />

<div class="book_post">
<% @categories.each do |category| %>
    <small>
      <h2><%= link_to category.name, category %></h2>

    </small>
<% end %>
</div>

app/views/categories/show.html.erb
<h1>Книги по категории "<%= @category.name %>"</h1>
<hr>

<% if @category.books.empty? %>
  <h2>Книги отсутствуют в данной категории</h2>
<% else %>
  <%= render @books %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Библиотека</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%= books_path %>">Все книги<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%= authors_path %>">Все авторы</a>
      <a class="nav-item nav-link" href="<%= categories_path %>" >Все категории</a>
    </div>

    <%= link_to 'Добавить книгу', new_book_path, class: 'btn btn-primary pull-xs-right' %>
    <% if user_signed_in? %>
    <%= link_to 'Выход', destroy_user_session_path, method: :delete, class: 'btn btn-primary add_somethg pull-xs-right' %>
    <% else %>
    <%= link_to 'Вход', new_user_session_path, class: 'btn btn-primary add_somethg pull-xs-right' %>
    <%= link_to 'Регистрация', new_user_registration_path, class: 'btn btn-primary add_somethg pull-xs-right' %>
    <% end %>

  </div>
</nav>
</div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert"> </button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
    <%= yield %>
    </div>
  </body>
</html>